fileserver:
    image: neocxf/phantom-jre8:2.1.1
    container_name: fileserver
    working_dir: /app
    ports:
      - "8091:80"
    volumes:
      - ../dsone-fileserver-boot/target/dsone-fileserver-boot.jar:/app/fileserver.jar
    net: "host"
    command: java -jar fileserver.jar --server.port=8091